
# Boss-bars ^_^
boss-bars:

  # The delay with which boss-bars are changed (in seconds)
  delay: 60

  # Possible color options:
  # BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  #
  # Possible segmented options:
  # SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20, SOLID
  #
  # Possible progress options:
  # real number from 0 to 1

  bars:
    1:
      color: BLUE
      segmented: SEGMENTED_6
      progress: 1
      text: '&6&lHello'
    2:
      color: RED
      segmented: SEGMENTED_20
      progress: 0.228
      text: '&0&lGoodbye'

# Action-bars O_o
action-bars:

  # The delay with which action-bars are displayed (in seconds)
  delay: 60

  bars:
    kek-bar:
      text: 'kek'
    lol-bar:
      text: 'lol'

# Chat messages X_X
chat-messages:

  # The delay with which messages are printed in chat (in seconds)
  delay: 10

  messages:
    1:
      raw: false
      text:
        - 'ds'
    2:
      raw: true
      text:
        - '<>&4sd <1,2>&l&6&love'

  hover:
    1: '&eGood'
    2: '&eBad'
  execute:
    1: 'A| hubs'
    2: 'U| http://hubsmc.ru'
    3: 'E| help'

periodic-feed:
  delay: 60
  cmd-to-console: 'say no'
  cmd-to-player: 'say yes'

mysql:
  use: false
  host: localhost
  port: 3306
  database: minecraft
  table: PLAYERDATA
  username: Minecraft
  password: pass123

# DO NOT CHANGE THIS!
config-version: 3
